import * as T from '^/types';


export const generalErrorDescription = {
  [T.Language.KO_KR]: '새로고침(F5)을 눌러 다시 시도해 주세요. 문제가 계속되면 \'지원\' 채팅창을 통해 오류를 보고해 주세요.',
  [T.Language.EN_US]: 'Please refresh(F5) and try again. If the error persists, please report through the "Help" chat box.',
};

export const ErrorText = {
  measurementPicker: {
    title: {
      [T.Language.KO_KR]: '측정 도구에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Measurement Picker.',
    },
    description: generalErrorDescription,
  },
  mapViewBar: {
    title: {
      [T.Language.KO_KR]: '지도 비교 기능에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Compare Map Feature.',
    },
    description: generalErrorDescription,
  },
  mapMode: {
    title: {
      [T.Language.KO_KR]: '화면 설정 기능에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Screen Setting Feature.',
    },
    description: generalErrorDescription,
  },
  mapController: {
    title: {
      [T.Language.KO_KR]: '지도 제어 기능에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in Map Controller.',
    },
    description: generalErrorDescription,
  },
  notification: {
    title: {
      [T.Language.KO_KR]: '알림 기능에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in Notifications.',
    },
    description: generalErrorDescription,
  },
  topBarScreenTitle: {
    title: {
      [T.Language.KO_KR]: '데이터 세트 제목 기능에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Data Set Title Feature.',
    },
    description: generalErrorDescription,
  },
  contentsTabbar: {
    title: {
      [T.Language.KO_KR]: '왼쪽 사이드 바에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Left Side Bar.',
    },
    description: generalErrorDescription,
  },
  contentsList: {
    title: {
      [T.Language.KO_KR]: '컨텐츠 목록을 불러오는 데 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred while retrieving Contents List.',
    },
    description: generalErrorDescription,
  },
  contentsSidebarHeader: {
    title: {
      [T.Language.KO_KR]: '날짜 선택 기능에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Date Selection Feature.',
    },
    description: generalErrorDescription,
  },
  contentsListMarkerItem: {
    title: {
      [T.Language.KO_KR]: '위치 컨텐츠에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Location Contents.',
    },
    description: generalErrorDescription,
  },
  contentsListAreaItem: {
    title: {
      [T.Language.KO_KR]: '면적 컨텐츠에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Area Contents.',
    },
    description: generalErrorDescription,
  },
  contentsListBlueprintItem: {
    title: {
      [T.Language.KO_KR]: '도면 컨텐츠에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the CAD Overlay Contents.',
    },
    description: generalErrorDescription,
  },
  contentsListLengthItem: {
    title: {
      [T.Language.KO_KR]: '거리 컨텐츠에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Distance Contents.',
    },
    description: generalErrorDescription,
  },
  contentsListMapAndDSMItem: {
    title: {
      [T.Language.KO_KR]: '정사영상 또는 수치표면모델 데이터에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Orthomosiac or DSM Data.',
    },
    description: generalErrorDescription,
  },
  contentsListPointCloudItem: {
    title: {
      [T.Language.KO_KR]: '포인트클라우드 데이터에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Point Cloud Data.',
    },
    description: generalErrorDescription,
  },
  contentsListThreeDOrthoItem: {
    title: {
      [T.Language.KO_KR]: '3D 정사영상 데이터에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the 3D Orthomosaic Data.',
    },
    description: generalErrorDescription,
  },
  contentsListVolumeItem: {
    title: {
      [T.Language.KO_KR]: '체적 컨텐츠에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Volume Contents.',
    },
    description: generalErrorDescription,
  },
  contentsListESSModelItem: {
    title: {
      [T.Language.KO_KR]: '장비에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Equipment Content.',
    },
    description: generalErrorDescription,
  },
  contentsListESSArrowItem: {
    title: {
      [T.Language.KO_KR]: '경로에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Path Content.',
    },
    description: generalErrorDescription,
  },
  contentsListESSTextItem: {
    title: {
      [T.Language.KO_KR]: '텍스트에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Text Content.',
    },
    description: generalErrorDescription,
  },
  twoDDisplay: {
    title: {
      [T.Language.KO_KR]: '2D 화면에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the 2D Screen.',
    },
    description: generalErrorDescription,
  },
  threeDDisplay: {
    title: {
      [T.Language.KO_KR]: '포인트클라우드 화면에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Point Cloud Screen.',
    },
    description: generalErrorDescription,
  },
  cesiumViewer: {
    title: {
      [T.Language.KO_KR]: '3D 화면에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the 3D Screen.',
    },
    description: generalErrorDescription,
  },
  screenPicker: {
    title: {
      [T.Language.KO_KR]: '데이터 세트 목록에 오류가 발생했습니다.',
      [T.Language.EN_US]: 'Error has occurred in the Data Set List.',
    },
    description: generalErrorDescription,
  },
  retryDeleteGroup: {
    title: {
      [T.Language.KO_KR]: '그룹에 새 데이터 확인',
      [T.Language.EN_US]: 'New Data was Found',
    },
    description: {
      [T.Language.KO_KR]: '이 그룹에서 새로운 데이터를 발견했습니다. 다른 사용자가 최근 생성한 데이터일 수 있습니다. 삭제 전 확인하시기 바랍니다.',
      [T.Language.EN_US]: 'New data was found within this group. This may be generated by another user recently, so please check before deleting.',
    },
  },
};

